Exclude wait for build to test action

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -6,29 +6,29 @@ on:
   pull_request:
     branches: [ "main" ]
 jobs:
-  wait-for-img:
-    name: "Wait for Image Build"
-    runs-on: ubuntu-latest
-    steps:
-      - uses: autotelic/action-wait-for-status-check@v1
-        id: wait-for-build
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          # Context for which we should look for the matching status
-          statusName: ${{ 'main-lifecycle-mgr-build' }}
-          timeoutSeconds: 300 # 5 mins due to flakiness of build speed in prow
-          intervalSeconds: 10
-      - name: Exit If Failing Build Requirement
-        if: steps.wait-for-build.outputs.state != 'success'
-        run: |
-          echo "Image build did not succeed, skipping Smoke Test!"
-          exit 1
+#  wait-for-img:
+#    name: "Wait for Image Build"
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: autotelic/action-wait-for-status-check@v1
+#        id: wait-for-build
+#        with:
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          # Context for which we should look for the matching status
+#          statusName: ${{ 'main-lifecycle-mgr-build' }}
+#          timeoutSeconds: 300 # 5 mins due to flakiness of build speed in prow
+#          intervalSeconds: 10
+#      - name: Exit If Failing Build Requirement
+#        if: steps.wait-for-build.outputs.state != 'success'
+#        run: |
+#          echo "Image build did not succeed, skipping Smoke Test!"
+#          exit 1
   e2e-integration:
     strategy:
       matrix:
         cli-stability: [ "unstable" ]
     name: "Run E2E tests"
-    needs: [wait-for-img]
+#    needs: [wait-for-img]
     runs-on: ubuntu-latest
     env:
       K3D_VERSION: v5.4.7
